service: EmptorTrialProject

provider:
  name: aws
  runtime: python3.7

functions:
  handle_url:
    handler: trialproject.index.handle_url

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux

package:
  exclude:
    - node_modules/**
